# Site settings
title: Otus Lisp
email: yuriy.chumak@mail.com
description: Otus Lisp project page
baseurl: "/OL"
url: "http://yuriy-chumak.github.io"
github_username:  yuriy-chumak

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
