# Site settings
title: Ol (Otus Lisp)
email: yuriy.chumak@mail.com
description: Otus Lisp project page
baseurl: "/ol"
url: "http://yuriy-chumak.github.io"

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
